server:
  port: 8081

spring:
  application:
    name: "ms-procut"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, refresh, health
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

info:
  app:
    name: "ms-product"
    description: "A microservice of product"
    version: 1.0.0
